@host=http://localhost:8000
###

GET /health


###
POST /register
Content-Type: application/json

{
    "email": "juan@garn.dev",
    "password": "123456",
    "name":"juan"
}

###

POST /login
Content-Type: application/json

{
    "email": "juan@garn.dev",
    "password": "123456"
}