version: '3.1'

services:
  deno:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: deno task dev
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3306:3306
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  swagger_ui:
    container_name: swagger_ui_service
    image: swaggerapi/swagger-ui
    ports:
      - "8105:8080"
    volumes:
      - ./openapi.yml:/openapi.yml
    environment:
      SWAGGER_JSON: /openapi.yml
