version: '3.2'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    container_name: api-oak
    volumes:
      - .:/app
    command: deno task dev
    healthcheck:
      # test: ["CMD","curl", "--fail", "--silent", "--output", "/dev/null", "http://api:8000/health"]
      test: curl --fail http://localhost:8000/health || exit 1
      interval: 30s
      retries: 1
      start_period: 2s
      timeout: 1s
    depends_on:
      - db
  migrate:
    build: .
    container_name: nessie-migrate
    volumes:
      - .:/app
    command: deno task migrate
    depends_on:
      api:
        condition: service_healthy
      db:
        condition: service_started
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3306:3306
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  swagger_ui:
    container_name: swagger_ui_service
    image: swaggerapi/swagger-ui
    ports:
      - "8105:8080"
    volumes:
      - ./openapi.yml:/openapi.yml
    environment:
      SWAGGER_JSON: /openapi.yml
